/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ocatve;

import AdminMenu.Admin;
import javax.swing.JOptionPane;

/**
 *
 * @author Anggo
 */
public class logadmin extends javax.swing.JFrame {
    private static final String ADMIN_USERNAME = "admin";
    private static final String ADMIN_PASSWORD = "admin123";
    /**
     * Creates new form logadmin
     */
    public logadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminpanel = new javax.swing.JPanel();
        admin_label = new javax.swing.JLabel();
        adminpic = new javax.swing.JLabel();
        hiadmin_label = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password_text_filed = new javax.swing.JPasswordField();
        cancelbutton = new javax.swing.JButton();
        signinbutton = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_label.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        admin_label.setForeground(new java.awt.Color(255, 255, 255));
        admin_label.setText("ADMIN");
        adminpanel.add(admin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        adminpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Admin.png"))); // NOI18N
        adminpanel.add(adminpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 111, 102));

        hiadmin_label.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        hiadmin_label.setForeground(new java.awt.Color(255, 255, 255));
        hiadmin_label.setText("Hi Admin");
        adminpanel.add(hiadmin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        adminpanel.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 35));
        adminpanel.add(password_text_filed, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 140, 35));

        cancelbutton.setBackground(new java.awt.Color(153, 153, 153));
        cancelbutton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        cancelbutton.setText("cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        adminpanel.add(cancelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 101, 33));

        signinbutton.setBackground(new java.awt.Color(153, 153, 153));
        signinbutton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        signinbutton.setText("Sign In");
        signinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbuttonActionPerformed(evt);
            }
        });
        adminpanel.add(signinbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 98, 33));

        username_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText("Username :");
        adminpanel.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 99, 35));

        password_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password_label.setForeground(new java.awt.Color(255, 255, 255));
        password_label.setText("Password :");
        adminpanel.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 99, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N
        adminpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 330));

        getContentPane().add(adminpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbuttonActionPerformed
       String enteredUsername = username_field.getText();
    String enteredPassword = new String(password_text_filed.getPassword());

    if (enteredUsername.equals(ADMIN_USERNAME) && enteredPassword.equals(ADMIN_PASSWORD)) {
        Admin admin = new Admin();
        admin.setLocationRelativeTo(null);
        admin.setVisible(true);
        setVisible(false);
    } else {
        JOptionPane.showMessageDialog(this, "Invalid admin credentials.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_signinbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true); // Corrected typo here
        log.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_cancelbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
            logadmin frame = new logadmin();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_label;
    private javax.swing.JPanel adminpanel;
    private javax.swing.JLabel adminpic;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JLabel hiadmin_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel password_label;
    private javax.swing.JPasswordField password_text_filed;
    private javax.swing.JButton signinbutton;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
