/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ocatve;

import AttendeeMenu.logattendee;

/**
 *
 * @author Anggo
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        logpanel = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        adminbuttonLOG = new javax.swing.JButton();
        organizerbuttonLOG = new javax.swing.JButton();
        attendeebuttonLOG = new javax.swing.JButton();
        logpic = new javax.swing.JLabel();
        exitbutton = new javax.swing.JButton();
        backlabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_label.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        welcome_label.setForeground(new java.awt.Color(255, 255, 255));
        welcome_label.setText("Welcome to Octave!");
        logpanel.add(welcome_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 389, -1));

        adminbuttonLOG.setBackground(new java.awt.Color(204, 204, 204));
        adminbuttonLOG.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        adminbuttonLOG.setText("ADMIN LOGIN");
        adminbuttonLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbuttonLOGActionPerformed(evt);
            }
        });
        logpanel.add(adminbuttonLOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 140, 50));

        organizerbuttonLOG.setBackground(new java.awt.Color(204, 204, 204));
        organizerbuttonLOG.setFont(new java.awt.Font("Segoe UI Semilight", 1, 10)); // NOI18N
        organizerbuttonLOG.setText("ORGANIZER LOGIN");
        organizerbuttonLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizerbuttonLOGActionPerformed(evt);
            }
        });
        logpanel.add(organizerbuttonLOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 140, 50));

        attendeebuttonLOG.setBackground(new java.awt.Color(204, 204, 204));
        attendeebuttonLOG.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        attendeebuttonLOG.setText("ATTENDEE MENU");
        attendeebuttonLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendeebuttonLOGActionPerformed(evt);
            }
        });
        logpanel.add(attendeebuttonLOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 140, 50));

        logpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.png"))); // NOI18N
        logpanel.add(logpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, 430));

        exitbutton.setBackground(new java.awt.Color(204, 204, 204));
        exitbutton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        exitbutton.setText("EXIT");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        logpanel.add(exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 140, 50));

        backlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        backlabel.setText("jLabel1");
        logpanel.add(backlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 820, 500));

        getContentPane().add(logpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminbuttonLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbuttonLOGActionPerformed
       logadmin admin = new logadmin();
       admin.setLocationRelativeTo(null);
       admin.setVisible(true); // Corrected typo here
       setVisible(false);
    }//GEN-LAST:event_adminbuttonLOGActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void organizerbuttonLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizerbuttonLOGActionPerformed
        // TODO add your handling code here:
        logorganizer organizer = new logorganizer();
        organizer.setLocationRelativeTo(null);
       organizer.setVisible(true); // Corrected typo here
       setVisible(false);
    }//GEN-LAST:event_organizerbuttonLOGActionPerformed

    private void attendeebuttonLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendeebuttonLOGActionPerformed
        // TODO add your handling code here:
        logattendee attendee = new  logattendee();
        attendee.setLocationRelativeTo(null);
        attendee.setVisible(true); // Corrected typo here
        setVisible(false);
    }//GEN-LAST:event_attendeebuttonLOGActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            login frame = new login();
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
            
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton adminbuttonLOG;
    public javax.swing.JButton attendeebuttonLOG;
    private javax.swing.JLabel backlabel;
    private javax.swing.JButton exitbutton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel logpanel;
    private javax.swing.JLabel logpic;
    public javax.swing.JButton organizerbuttonLOG;
    private javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
}
