/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AttendeeMenu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import ocatve.DatabaseManager;
/**
 *
 * @author Anggo
 */
public class Feedback extends javax.swing.JFrame {
    private int eventid;
    private int attendeeid;
    private String feedback;

    public Feedback() {
        initComponents();
    }

    public Feedback(String feedback) {
        this.feedback = feedback;
        initComponents();
    }

    public String getFeedback() {
        return feedback;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hiadmin_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        eventidField = new javax.swing.JTextField();
        signinbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        attendeeidField = new javax.swing.JTextField();
        username_label1 = new javax.swing.JLabel();
        feedbackField = new javax.swing.JTextField();
        username_label2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hiadmin_label.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        hiadmin_label.setForeground(new java.awt.Color(255, 255, 255));
        hiadmin_label.setText("Hi Attendee");
        getContentPane().add(hiadmin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        username_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText("EVENT ID :");
        getContentPane().add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 99, 35));

        password_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password_label.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 99, 35));

        eventidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventidFieldActionPerformed(evt);
            }
        });
        getContentPane().add(eventidField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, 35));

        signinbutton.setBackground(new java.awt.Color(153, 153, 153));
        signinbutton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        signinbutton.setText("ADD FEEDBACK");
        signinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(signinbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 33));

        cancelbutton.setBackground(new java.awt.Color(153, 153, 153));
        cancelbutton.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        cancelbutton.setText("CANCEL");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, 33));

        attendeeidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendeeidFieldActionPerformed(evt);
            }
        });
        getContentPane().add(attendeeidField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, 35));

        username_label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_label1.setForeground(new java.awt.Color(255, 255, 255));
        username_label1.setText("ID :");
        getContentPane().add(username_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 99, 35));

        feedbackField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackFieldActionPerformed(evt);
            }
        });
        getContentPane().add(feedbackField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, 30));

        username_label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_label2.setForeground(new java.awt.Color(255, 255, 255));
        username_label2.setText("FEEDBACK");
        getContentPane().add(username_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 99, 35));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel16.setText("jLabel4");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbuttonActionPerformed
         addFeedback();
    }//GEN-LAST:event_signinbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
       logattendee log = new logattendee();
       log.setLocationRelativeTo(null);
        log.setVisible(true); // Corrected typo here
        setVisible(false);
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void eventidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventidFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventidFieldActionPerformed

    private void attendeeidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendeeidFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendeeidFieldActionPerformed

    private void feedbackFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feedbackFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   private void addFeedback() {
    String eventIdStr = eventidField.getText();
    String attendeeIdStr = attendeeidField.getText();
    String feedbackText = feedbackField.getText();

    Integer eventId = validateAndConvertToInt(eventIdStr, "Event ID");
    Integer attendeeId = validateAndConvertToInt(attendeeIdStr, "Attendee ID");

    if (eventId == null || attendeeId == null) return;

    if (!isEventIdValid(eventId)) {
        JOptionPane.showMessageDialog(null, "Invalid Event ID.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!isAttendeeIdValid(attendeeId)) {
        JOptionPane.showMessageDialog(null, "Invalid Attendee ID.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    System.out.println("Adding feedback with eventId=" + eventId + ", attendeeId=" + attendeeId + ", feedbackText=" + feedbackText);
    DatabaseManager.insertFeedback(eventId, attendeeId, feedbackText);

    eventidField.setText("");
    attendeeidField.setText("");
    feedbackField.setText("");
}

    private Integer validateAndConvertToInt(String value, String fieldName) {
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, fieldName + " must be a number.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

      private boolean isEventIdValid(int eventId) {
        try {
            return DatabaseManager.isEventIdValid(eventId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error validating Event ID: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean isAttendeeIdValid(int attendeeId) {
        try {
            return DatabaseManager.isAttendeeIdValid(attendeeId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error validating Attendee ID: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Feedback().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attendeeidField;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JTextField eventidField;
    private javax.swing.JTextField feedbackField;
    private javax.swing.JLabel hiadmin_label;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel password_label;
    private javax.swing.JButton signinbutton;
    private javax.swing.JLabel username_label;
    private javax.swing.JLabel username_label1;
    private javax.swing.JLabel username_label2;
    // End of variables declaration//GEN-END:variables
}
