/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OrganizerMenu;

import AdminMenu.attendeemanagement.ADD_attendee;
import AdminMenu.attendeemanagement.EDIT_attendee;
import AdminMenu.eventsmanengment.ADD_event;
import AdminMenu.attendeemanagement.DELETE_attendee;
import AdminMenu.eventsmanengment.EDIT_event;
import AdminMenu.eventsmanengment.LIST_event;
import OrganizerMenu.paymentmangement.add_payment;
import OrganizerMenu.paymentmangement.view_payment;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ocatve.DatabaseManager;
import ocatve.login;

/**
 *
 * @author Anggo
 */
public class Organizer extends javax.swing.JFrame {
private int choice = 0; // Define the choice variable at the class level

    /**
     * Creates new form Organizer
     */
    public Organizer() {
        initComponents();
        loadEvents("");
        loadEvent("");
        loadAttendee("");
    }
public javax.swing.JTabbedPane getTabPane() {
        return TAB;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hiadmin_label = new javax.swing.JLabel();
        admin_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eventbutton = new javax.swing.JButton();
        attendeebutton = new javax.swing.JButton();
        apymentbuttoon = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        TAB = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        admin_label1 = new javax.swing.JLabel();
        upcomingevent1 = new javax.swing.JLabel();
        addevent = new javax.swing.JButton();
        editEventButton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        searcheventbutton = new javax.swing.JButton();
        searcheventlabel = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        eventtable = new javax.swing.JTable();
        listbutton = new javax.swing.JButton();
        countevent = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        admin_label3 = new javax.swing.JLabel();
        backbuttonattendee = new javax.swing.JButton();
        upcomingevent2 = new javax.swing.JLabel();
        addEventButton11 = new javax.swing.JButton();
        editEventButton8 = new javax.swing.JButton();
        editEventButton7 = new javax.swing.JButton();
        searchattendeebutton = new javax.swing.JButton();
        searchattendeelabel = new javax.swing.JTextField();
        countanttendee = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        attendeetable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        admin_label6 = new javax.swing.JLabel();
        paymentbutton = new javax.swing.JButton();
        viewpaymentbutton = new javax.swing.JButton();
        upcomingevent3 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        eventtable1 = new javax.swing.JTable();
        countevent1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hiadmin_label.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        hiadmin_label.setForeground(new java.awt.Color(255, 255, 255));
        hiadmin_label.setText("Oraganizer");
        jPanel1.add(hiadmin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        admin_label.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label.setForeground(new java.awt.Color(255, 255, 255));
        admin_label.setText("Dashbourd");
        jPanel1.add(admin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/organizer.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 119, -1));

        eventbutton.setBackground(new java.awt.Color(204, 204, 204));
        eventbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eventbutton.setText("Events");
        eventbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(eventbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 129, 32));

        attendeebutton.setBackground(new java.awt.Color(204, 204, 204));
        attendeebutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        attendeebutton.setText("Attendee ");
        attendeebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendeebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(attendeebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 129, 32));

        apymentbuttoon.setBackground(new java.awt.Color(204, 204, 204));
        apymentbuttoon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apymentbuttoon.setText("Payment");
        apymentbuttoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apymentbuttoonActionPerformed(evt);
            }
        });
        jPanel1.add(apymentbuttoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, 32));

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 129, 32));

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_label1.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label1.setForeground(new java.awt.Color(255, 255, 255));
        admin_label1.setText("Manage Events");
        jPanel2.add(admin_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        upcomingevent1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent1.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent1.setText("Upcoming Event!");
        jPanel2.add(upcomingevent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 340, 50));

        addevent.setBackground(new java.awt.Color(204, 204, 204));
        addevent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addevent.setText("ADD EVENT");
        addevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addeventActionPerformed(evt);
            }
        });
        jPanel2.add(addevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 129, 32));

        editEventButton.setBackground(new java.awt.Color(204, 204, 204));
        editEventButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editEventButton.setText("EDIT EVENT");
        editEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEventButtonActionPerformed(evt);
            }
        });
        jPanel2.add(editEventButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 129, 32));

        backbutton.setBackground(new java.awt.Color(204, 204, 204));
        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 90, 32));

        searcheventbutton.setBackground(new java.awt.Color(204, 204, 204));
        searcheventbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searcheventbutton.setText("SEARCH");
        searcheventbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcheventbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(searcheventbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 32));

        searcheventlabel.setBackground(new java.awt.Color(153, 255, 255));
        searcheventlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcheventlabelActionPerformed(evt);
            }
        });
        jPanel2.add(searcheventlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 150, 30));

        eventtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Event ID", "Name", "Date", "Time", "Hour", "Venue", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(eventtable);

        jPanel2.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 500, 150));

        listbutton.setBackground(new java.awt.Color(204, 204, 204));
        listbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listbutton.setText("list");
        listbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(listbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 40, 20));

        countevent.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        countevent.setForeground(new java.awt.Color(255, 255, 255));
        countevent.setText("20");
        countevent.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                counteventAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(countevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 70));

        TAB.addTab("Event ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_label3.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label3.setForeground(new java.awt.Color(255, 255, 255));
        admin_label3.setText("Manage Attendee");
        jPanel3.add(admin_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        backbuttonattendee.setBackground(new java.awt.Color(204, 204, 204));
        backbuttonattendee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbuttonattendee.setText("BACK");
        backbuttonattendee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonattendeeActionPerformed(evt);
            }
        });
        jPanel3.add(backbuttonattendee, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 90, 32));

        upcomingevent2.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent2.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent2.setText("Attendee");
        jPanel3.add(upcomingevent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        addEventButton11.setBackground(new java.awt.Color(204, 204, 204));
        addEventButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEventButton11.setText("ADD ");
        addEventButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(addEventButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, 32));

        editEventButton8.setBackground(new java.awt.Color(204, 204, 204));
        editEventButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editEventButton8.setText("EDIT ");
        editEventButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEventButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(editEventButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 80, 32));

        editEventButton7.setBackground(new java.awt.Color(204, 204, 204));
        editEventButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editEventButton7.setText("DELETE");
        editEventButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEventButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(editEventButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 80, 32));

        searchattendeebutton.setBackground(new java.awt.Color(204, 204, 204));
        searchattendeebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchattendeebutton.setText("SEARCH");
        searchattendeebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchattendeebuttonActionPerformed(evt);
            }
        });
        jPanel3.add(searchattendeebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 90, 32));

        searchattendeelabel.setBackground(new java.awt.Color(153, 255, 255));
        searchattendeelabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchattendeelabelActionPerformed(evt);
            }
        });
        jPanel3.add(searchattendeelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, 30));

        countanttendee.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        countanttendee.setForeground(new java.awt.Color(255, 255, 255));
        countanttendee.setText("20");
        countanttendee.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                countanttendeeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(countanttendee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 70));

        attendeetable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attendeetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ST2024-0001", "Andre M.", "Adiii@UN"},
                {"ST2024-00002", "Joemar A.", "Joemar@UN"},
                {"ST2024-0003", "Jan P.", "Jan@UN"},
                {"ST20240-0004", "Judi G.", "Judi@UN"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Attendee ID", "Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(attendeetable);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 520, 150));

        TAB.addTab("Attendee Register", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_label6.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label6.setForeground(new java.awt.Color(255, 255, 255));
        admin_label6.setText("Manage Payment");
        jPanel5.add(admin_label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        paymentbutton.setBackground(new java.awt.Color(204, 204, 204));
        paymentbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentbutton.setText("Add Payment");
        paymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbuttonActionPerformed(evt);
            }
        });
        jPanel5.add(paymentbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 32));

        viewpaymentbutton.setBackground(new java.awt.Color(204, 204, 204));
        viewpaymentbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewpaymentbutton.setText("View Payments");
        viewpaymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpaymentbuttonActionPerformed(evt);
            }
        });
        jPanel5.add(viewpaymentbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 32));

        upcomingevent3.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent3.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent3.setText("Event!");
        jPanel5.add(upcomingevent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setText("BACK");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 32));

        eventtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event ID", "Name", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane14.setViewportView(eventtable1);

        jPanel5.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 380, 170));

        countevent1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        countevent1.setForeground(new java.awt.Color(255, 255, 255));
        countevent1.setText("20");
        countevent1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                countevent1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel5.add(countevent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 60, 70));

        TAB.addTab("Payment Process", jPanel5);

        jPanel1.add(TAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 570, 338));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 790, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventbuttonActionPerformed
 // TODO add your handling code here:
        TAB.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_eventbuttonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        login log = new login();
        log.setLocationRelativeTo(null);
        log.setVisible(true); // Corrected typo here
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void editEventButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEventButton7ActionPerformed
  choice = 2; // Update the choice variable
        DELETE_attendee delete = new  DELETE_attendee(choice);
        delete.setLocationRelativeTo(null);
        delete.setVisible(true); // Corrected typo here
        setVisible(false);   
    }//GEN-LAST:event_editEventButton7ActionPerformed

    private void editEventButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEventButton8ActionPerformed
  choice = 2; // Update the choice variable
        EDIT_attendee edit = new  EDIT_attendee(choice);
         edit.setLocationRelativeTo(null);
         edit.setVisible(true); // Corrected typo here
        setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_editEventButton8ActionPerformed

    private void addEventButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventButton11ActionPerformed
        choice = 2; // Update the choice variable
    ADD_attendee add = new ADD_attendee(choice, "", ""); // Pass the choice value to the constructor
    add.setLocationRelativeTo(null);
    add.setVisible(true); // Corrected typo here
    setVisible(false); 
    }//GEN-LAST:event_addEventButton11ActionPerformed

    private void backbuttonattendeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonattendeeActionPerformed
 // TODO add your handling code here:
        TAB.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonattendeeActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
       
        TAB.setSelectedIndex(0);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void editEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEventButtonActionPerformed
  // TODO add your handling code here:
   choice = 2; // Correctly update the choice variable        // TODO add your handling code here:
        EDIT_event edit = new EDIT_event(choice);
        edit.setLocationRelativeTo(null);
        edit.setVisible(true); // Corrected typo here
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_editEventButtonActionPerformed

    private void addeventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addeventActionPerformed
        choice = 2; // Correctly update the choice variable        // TODO add your handling code here:
        ADD_event add = new ADD_event(choice,"", "", "", "", "", "");
        add.setLocationRelativeTo(null);
        add.setVisible(true); // Corrected typo here
        setVisible(false);
    }//GEN-LAST:event_addeventActionPerformed

    private void paymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbuttonActionPerformed
       add_payment payment = new  add_payment();
       payment.setLocationRelativeTo(null);
        payment.setVisible(true); // Corrected typo here
        setVisible(false);   
    }//GEN-LAST:event_paymentbuttonActionPerformed

    private void viewpaymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpaymentbuttonActionPerformed
        view_payment view = new  view_payment();
        view.setLocationRelativeTo(null);
        view.setVisible(true); // Corrected typo here
        setVisible(false); 
    }//GEN-LAST:event_viewpaymentbuttonActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
 // TODO add your handling code here:
        TAB.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void attendeebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendeebuttonActionPerformed
 // TODO add your handling code here:
        TAB.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_attendeebuttonActionPerformed

    private void apymentbuttoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apymentbuttoonActionPerformed
 // TODO add your handling code here:
        TAB.setSelectedIndex(2);        // TODO add your handling code here:
    }//GEN-LAST:event_apymentbuttoonActionPerformed

    private void listbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbuttonActionPerformed
        choice = 2; // Correctly update the choice variable
        LIST_event list = new LIST_event(choice);
        list.setLocationRelativeTo(null);
        list.setVisible(true); // Corrected typo here
        setVisible(false);

    }//GEN-LAST:event_listbuttonActionPerformed

    private void counteventAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_counteventAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_counteventAncestorAdded

    private void countevent1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_countevent1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_countevent1AncestorAdded

    private void searcheventlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcheventlabelActionPerformed

    }//GEN-LAST:event_searcheventlabelActionPerformed

    private void searcheventbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcheventbuttonActionPerformed
        String searchTerm = searcheventlabel.getText().trim();
        loadEvents(searchTerm);
    }//GEN-LAST:event_searcheventbuttonActionPerformed

    private void searchattendeebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchattendeebuttonActionPerformed
         String searchTerm = searchattendeelabel.getText().trim();
        loadAttendee(searchTerm);
    }//GEN-LAST:event_searchattendeebuttonActionPerformed

    private void searchattendeelabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchattendeelabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchattendeelabelActionPerformed

    private void countanttendeeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_countanttendeeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_countanttendeeAncestorAdded

    /**
     * @param args the command line arguments
     */
    private void loadEvents(String searchTerm) {
        DefaultTableModel model = (DefaultTableModel) eventtable.getModel();
        model.setRowCount(0); // Clear existing data

        String sql = "SELECT * FROM events WHERE id LIKE ? OR name LIKE ? OR date LIKE ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            String likeSearchTerm = "%" + searchTerm + "%";
            pstmt.setString(1, likeSearchTerm);
            pstmt.setString(2, likeSearchTerm);
            pstmt.setString(3, likeSearchTerm);

            try (ResultSet rs = pstmt.executeQuery()) {
                int count = 0;
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("name"),
                        rs.getString("date"),
                        rs.getString("time"),
                        rs.getString("duration"),
                        rs.getString("venue"),
                        rs.getString("description")
                    });
                    count++;
                }
                countevent.setText(String.valueOf(count));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Failed to load events: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadEvent(String searchTerm) {
        DefaultTableModel model = (DefaultTableModel) eventtable1.getModel();
        model.setRowCount(0); // Clear existing data

        String sql = "SELECT * FROM events WHERE id LIKE ? OR name LIKE ? OR date LIKE ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            String likeSearchTerm = "%" + searchTerm + "%";
            pstmt.setString(1, likeSearchTerm);
            pstmt.setString(2, likeSearchTerm);
            pstmt.setString(3, likeSearchTerm);

            try (ResultSet rs = pstmt.executeQuery()) {
                int count = 0;
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("name"),
                        rs.getString("date"),
                        rs.getString("time"),
                  
                    });
                    count++;
                }
                countevent1.setText(String.valueOf(count));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Failed to load events: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadAttendee(String searchTerm) {
        DefaultTableModel model = (DefaultTableModel) attendeetable.getModel();
        model.setRowCount(0);  // Clear existing data

        String sql = "SELECT * FROM attendees WHERE id = ? OR name LIKE ? OR email LIKE ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setString(1, "%" + searchTerm + "%");
            pstmt.setString(2, "%" + searchTerm + "%");
            pstmt.setString(3, "%" + searchTerm + "%");

            try (ResultSet rs = pstmt.executeQuery()) {
                int count = 0;
                while (rs.next()) {
                    int id = rs.getInt("id");
                    String name = rs.getString("name");
                    String email = rs.getString("email");

                    model.addRow(new Object[]{id, name, email});
                    count++;
                }
                countanttendee.setText(String.valueOf(count));  // Update the count label
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Organizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Organizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Organizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Organizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Organizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TAB;
    private javax.swing.JButton addEventButton11;
    private javax.swing.JButton addevent;
    private javax.swing.JLabel admin_label;
    private javax.swing.JLabel admin_label1;
    private javax.swing.JLabel admin_label3;
    private javax.swing.JLabel admin_label6;
    private javax.swing.JButton apymentbuttoon;
    private javax.swing.JButton attendeebutton;
    private javax.swing.JTable attendeetable;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton backbuttonattendee;
    private javax.swing.JLabel countanttendee;
    private javax.swing.JLabel countevent;
    private javax.swing.JLabel countevent1;
    private javax.swing.JButton editEventButton;
    private javax.swing.JButton editEventButton7;
    private javax.swing.JButton editEventButton8;
    private javax.swing.JButton eventbutton;
    private javax.swing.JTable eventtable;
    private javax.swing.JTable eventtable1;
    private javax.swing.JLabel hiadmin_label;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton listbutton;
    private javax.swing.JButton paymentbutton;
    private javax.swing.JButton searchattendeebutton;
    private javax.swing.JTextField searchattendeelabel;
    private javax.swing.JButton searcheventbutton;
    private javax.swing.JTextField searcheventlabel;
    private javax.swing.JLabel upcomingevent1;
    private javax.swing.JLabel upcomingevent2;
    private javax.swing.JLabel upcomingevent3;
    private javax.swing.JButton viewpaymentbutton;
    // End of variables declaration//GEN-END:variables

   
}
