/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminMenu.suppliesmanament;

import AdminMenu.Admin;
import ocatve.DatabaseManager;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Anggo
 */
public class DELETE_supplies extends javax.swing.JFrame {

    /**
     * Creates new form DELETE_event
     */
    public DELETE_supplies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        supplyIDLabel = new javax.swing.JTextField();
        suppliesNameLabel = new javax.swing.JTextField();
        suppliesQuantityLabel = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        suppliespriceLabel = new javax.swing.JTextField();
        searchBT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/addProduct.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setAutoscrolls(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 103, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Supply Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Supply id:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Quantity:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, -1));

        supplyIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplyIDLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplyIDLabelActionPerformed(evt);
            }
        });
        jPanel1.add(supplyIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 70, -1));

        suppliesNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        suppliesNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliesNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(suppliesNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, -1));

        suppliesQuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        suppliesQuantityLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliesQuantityLabelActionPerformed(evt);
            }
        });
        jPanel1.add(suppliesQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, -1));

        deletebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 102, 40));

        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBT.setText("CANCEL");
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("DELETE Supplies");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Price:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, -1));

        suppliespriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        suppliespriceLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliespriceLabelActionPerformed(evt);
            }
        });
        jPanel1.add(suppliespriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 160, -1));

        searchBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBT.setText("SEARCH");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        jPanel1.add(searchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 80, 26));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 400, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supplyIDLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplyIDLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplyIDLabelActionPerformed

    private void suppliesNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliesNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliesNameLabelActionPerformed

    private void suppliesQuantityLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliesQuantityLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliesQuantityLabelActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
 try {
            int supplyID = Integer.parseInt(supplyIDLabel.getText().trim());
            deleteSupply(supplyID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Supply ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTActionPerformed
Admin admin = new Admin();
admin.setLocationRelativeTo(null);
        admin.setVisible(true);
        admin.getTabPane().setSelectedIndex(3); // Access TAB via the Admin instance
        setVisible(false);  
    }//GEN-LAST:event_cancelBTActionPerformed

    private void suppliespriceLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliespriceLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliespriceLabelActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
  try {
            int supplyID = Integer.parseInt(supplyIDLabel.getText().trim());
            searchSupply(supplyID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Supply ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBTActionPerformed

    /**
     * @param args the command line arguments
     */
     private void searchSupply(int supplyID) {
        String sql = "SELECT * FROM supplies WHERE id = ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setInt(1, supplyID);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                suppliesNameLabel.setText(rs.getString("name"));
                suppliesQuantityLabel.setText(rs.getString("quantity"));
                suppliespriceLabel.setText(rs.getString("price"));
            } else {
                JOptionPane.showMessageDialog(null, "Supply not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteSupply(int supplyID) {
        String sql = "DELETE FROM supplies WHERE id = ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setInt(1, supplyID);
            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Supply deleted successfully.");
                suppliesNameLabel.setText("");
                suppliesQuantityLabel.setText("");
                suppliespriceLabel.setText("");
                supplyIDLabel.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Supply not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE_supplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE_supplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE_supplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE_supplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE_supplies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBT;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchBT;
    private javax.swing.JTextField suppliesNameLabel;
    private javax.swing.JTextField suppliesQuantityLabel;
    private javax.swing.JTextField suppliespriceLabel;
    private javax.swing.JTextField supplyIDLabel;
    // End of variables declaration//GEN-END:variables
}
