/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminMenu;
import ocatve.DatabaseManager;

import AdminMenu.attendeemanagement.ADD_attendee;
import AdminMenu.attendeemanagement.EDIT_attendee;
import AdminMenu.attendeemanagement.LIST_attendee;
import AdminMenu.eventsmanengment.ADD_event;
import AdminMenu.attendeemanagement.DELETE_attendee;
import AdminMenu.eventsmanengment.DELETE_event;
import AdminMenu.eventsmanengment.EDIT_event;
import AdminMenu.eventsmanengment.LIST_event;
import AdminMenu.organizermaegement.ADD_organizer;
import AdminMenu.organizermaegement.EDIT_organizer;
import AdminMenu.organizermaegement.DELETE_organizer;
import AdminMenu.organizermaegement.LIST_organizer;
import AdminMenu.repormangement.feedbackSUM;
import AdminMenu.repormangement.financialSUM;
import AdminMenu.suppliesmanament.ADD_supplies;
import AdminMenu.suppliesmanament.DELETE_supplies;
import AdminMenu.suppliesmanament.EDIT_supplies;
import AdminMenu.suppliesmanament.LIST_supplies;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ocatve.login;

/**
 *
 * @author Anggo
 */
public class Admin extends javax.swing.JFrame {
private int choice = 0; // Define the choice variable at the class level

    /**
     * Creates new form Admin
     */
    public Admin() {
      
        initComponents();
        loadOrganizers("");  // Load all organizers when the frame is initialized
         loadEvents("");
         loadEvent("");
         loadAttendee("");
         loadSupplies("");
    }
     public javax.swing.JTabbedPane getTabPane() {
        return TAB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hiadmin_label = new javax.swing.JLabel();
        admin_label = new javax.swing.JLabel();
        dashbourdbutton = new javax.swing.JButton();
        manageeventbutton = new javax.swing.JButton();
        manageattendeebutton = new javax.swing.JButton();
        managesuppliesbutton = new javax.swing.JButton();
        manageorganizerbutton = new javax.swing.JButton();
        viewreportsbutton = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TAB = new javax.swing.JTabbedPane();
        dashbourd = new javax.swing.JPanel();
        backbutton = new javax.swing.JButton();
        upcomingevent = new javax.swing.JLabel();
        Product_Panel3 = new javax.swing.JPanel();
        Suppliescount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        countsupplies = new javax.swing.JLabel();
        Product_Panel4 = new javax.swing.JPanel();
        attendeelabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        attendeecount = new javax.swing.JLabel();
        Product_Panel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        organizerlabel2 = new javax.swing.JLabel();
        countorganizer = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        eventtable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        countanttendee = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        EVENT = new javax.swing.JPanel();
        admin_label1 = new javax.swing.JLabel();
        upcomingevent1 = new javax.swing.JLabel();
        addEventButton = new javax.swing.JButton();
        editEventbutton = new javax.swing.JButton();
        backbutton1 = new javax.swing.JButton();
        listbutton = new javax.swing.JButton();
        deleteEventButton3 = new javax.swing.JButton();
        searcheventbutton = new javax.swing.JButton();
        searcheventlabel = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        eventtable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ATTENDEE_PANEL = new javax.swing.JPanel();
        upcomingevent2 = new javax.swing.JLabel();
        admin_label3 = new javax.swing.JLabel();
        deleteattenddetButton4 = new javax.swing.JButton();
        addattendeeButton = new javax.swing.JButton();
        editattendeetButton6 = new javax.swing.JButton();
        backbutton2 = new javax.swing.JButton();
        searchattendeelabel = new javax.swing.JTextField();
        searchattendeebutton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        attendeetable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        SUPPLIESPANEL = new javax.swing.JPanel();
        admin_label5 = new javax.swing.JLabel();
        upcomingevent3 = new javax.swing.JLabel();
        deletesuppliestButton = new javax.swing.JButton();
        editsuppliesButton = new javax.swing.JButton();
        addsuppliesButton = new javax.swing.JButton();
        backbutton3 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        supplieastable = new javax.swing.JTable();
        searchsuppliesbutton = new javax.swing.JButton();
        searchsupplieslabel = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ORGANIZERPANEL = new javax.swing.JPanel();
        admin_label7 = new javax.swing.JLabel();
        upcomingevent4 = new javax.swing.JLabel();
        searchorganizerbutton = new javax.swing.JButton();
        searchorgaizerlabel = new javax.swing.JTextField();
        deleteOrganizerButton = new javax.swing.JButton();
        editorganierButton = new javax.swing.JButton();
        addorganizerButton = new javax.swing.JButton();
        backbutton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        organizertable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        REPORTPANEL = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        upcomingevent5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LISTATTENDEEBUTTON = new javax.swing.JButton();
        FEEDBACKSUMMARYBUTTON = new javax.swing.JButton();
        FINANCALBUTTON = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LISTORGANIZZERBUTTON = new javax.swing.JButton();
        backbutton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        suppliesbutton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hiadmin_label.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        hiadmin_label.setForeground(new java.awt.Color(255, 255, 255));
        hiadmin_label.setText("Admin");
        jPanel2.add(hiadmin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        admin_label.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label.setForeground(new java.awt.Color(255, 255, 255));
        admin_label.setText("Dashbourd");
        jPanel2.add(admin_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        dashbourdbutton.setBackground(new java.awt.Color(204, 204, 204));
        dashbourdbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashbourdbutton.setText("Dashboard");
        dashbourdbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashbourdbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(dashbourdbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 129, 32));

        manageeventbutton.setBackground(new java.awt.Color(204, 204, 204));
        manageeventbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageeventbutton.setText("Manage Events");
        manageeventbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageeventbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(manageeventbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 129, 32));

        manageattendeebutton.setBackground(new java.awt.Color(204, 204, 204));
        manageattendeebutton.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        manageattendeebutton.setText("Manage Attendees");
        manageattendeebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageattendeebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(manageattendeebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 130, 32));

        managesuppliesbutton.setBackground(new java.awt.Color(204, 204, 204));
        managesuppliesbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        managesuppliesbutton.setText("Manage Supplies");
        managesuppliesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managesuppliesbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(managesuppliesbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 129, 32));

        manageorganizerbutton.setBackground(new java.awt.Color(204, 204, 204));
        manageorganizerbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageorganizerbutton.setText("Edit Organizers");
        manageorganizerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageorganizerbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(manageorganizerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 129, 32));

        viewreportsbutton.setBackground(new java.awt.Color(204, 204, 204));
        viewreportsbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewreportsbutton.setText("View Reports");
        viewreportsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreportsbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(viewreportsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 129, 32));

        exit.setBackground(new java.awt.Color(204, 204, 204));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 129, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Admin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 119, -1));

        dashbourd.setBackground(new java.awt.Color(153, 0, 153));
        dashbourd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dashbourd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton.setBackground(new java.awt.Color(204, 204, 204));
        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        dashbourd.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 129, 32));

        upcomingevent.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent.setText("Upcoming Event!");
        dashbourd.add(upcomingevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        Product_Panel3.setBackground(new java.awt.Color(73, 190, 183));
        Product_Panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Suppliescount.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        Suppliescount.setForeground(new java.awt.Color(255, 255, 255));
        Suppliescount.setText("Supplies");
        Product_Panel3.add(Suppliescount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, 27));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Product_Icon.png"))); // NOI18N
        jLabel14.setText("jLabel4");
        Product_Panel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 40));

        countsupplies.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        countsupplies.setForeground(new java.awt.Color(255, 255, 255));
        countsupplies.setText("20");
        countsupplies.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                countsuppliesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Product_Panel3.add(countsupplies, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 70));

        dashbourd.add(Product_Panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 170, 80));

        Product_Panel4.setBackground(new java.awt.Color(73, 190, 183));
        Product_Panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendeelabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        attendeelabel1.setForeground(new java.awt.Color(255, 255, 255));
        attendeelabel1.setText("Attendee");
        Product_Panel4.add(attendeelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 27));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Staff_Icon.png"))); // NOI18N
        jLabel8.setText("jLabel4");
        Product_Panel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 40));

        attendeecount.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        attendeecount.setForeground(new java.awt.Color(255, 255, 255));
        attendeecount.setText("20");
        attendeecount.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                attendeecountAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Product_Panel4.add(attendeecount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 70));

        dashbourd.add(Product_Panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, 80));

        Product_Panel5.setBackground(new java.awt.Color(73, 190, 183));
        Product_Panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Staff_Icon.png"))); // NOI18N
        jLabel15.setText("jLabel4");
        Product_Panel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 40));

        organizerlabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        organizerlabel2.setForeground(new java.awt.Color(255, 255, 255));
        organizerlabel2.setText("Organizer");
        Product_Panel5.add(organizerlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 27));

        countorganizer.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        countorganizer.setForeground(new java.awt.Color(255, 255, 255));
        countorganizer.setText("20");
        countorganizer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                countorganizerAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Product_Panel5.add(countorganizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 70));

        dashbourd.add(Product_Panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 80));

        eventtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Event ID", "Name", "Date", "Time", "Hour", "Venue", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(eventtable1);

        dashbourd.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 480, 220));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel16.setText("jLabel4");
        dashbourd.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 500, 300));

        countanttendee.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        countanttendee.setForeground(new java.awt.Color(255, 255, 255));
        countanttendee.setText("20");
        countanttendee.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                countanttendeeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dashbourd.add(countanttendee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 60, 70));

        TAB.addTab("DASHBOARD", dashbourd);

        EVENT.setBackground(new java.awt.Color(153, 0, 153));
        EVENT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_label1.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label1.setForeground(new java.awt.Color(255, 255, 255));
        admin_label1.setText("Manage Events");
        EVENT.add(admin_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        upcomingevent1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent1.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent1.setText("Upcoming Event!");
        EVENT.add(upcomingevent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        addEventButton.setBackground(new java.awt.Color(204, 204, 204));
        addEventButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEventButton.setText("ADD EVENT");
        addEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventButtonActionPerformed(evt);
            }
        });
        EVENT.add(addEventButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 32));

        editEventbutton.setBackground(new java.awt.Color(204, 204, 204));
        editEventbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editEventbutton.setText("EDIT EVENT");
        editEventbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEventbuttonActionPerformed(evt);
            }
        });
        EVENT.add(editEventbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 110, 32));

        backbutton1.setBackground(new java.awt.Color(204, 204, 204));
        backbutton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton1.setText("BACK");
        backbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton1ActionPerformed(evt);
            }
        });
        EVENT.add(backbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 129, 32));

        listbutton.setBackground(new java.awt.Color(204, 204, 204));
        listbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listbutton.setText("list");
        listbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbuttonActionPerformed(evt);
            }
        });
        EVENT.add(listbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 40, 20));

        deleteEventButton3.setBackground(new java.awt.Color(204, 204, 204));
        deleteEventButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteEventButton3.setText("DELETE EVENT");
        deleteEventButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEventButton3ActionPerformed(evt);
            }
        });
        EVENT.add(deleteEventButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 130, 32));

        searcheventbutton.setBackground(new java.awt.Color(204, 204, 204));
        searcheventbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searcheventbutton.setText("SEARCH");
        searcheventbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcheventbuttonActionPerformed(evt);
            }
        });
        EVENT.add(searcheventbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 90, 32));

        searcheventlabel.setBackground(new java.awt.Color(153, 255, 255));
        searcheventlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcheventlabelActionPerformed(evt);
            }
        });
        EVENT.add(searcheventlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 150, 30));

        eventtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Event ID", "Name", "Date", "Time", "Hour", "Venue", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(eventtable);

        EVENT.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 470, 220));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel17.setText("jLabel4");
        EVENT.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 500, 330));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(EVENT, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EVENT, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        TAB.addTab("EVENTS", jPanel3);

        ATTENDEE_PANEL.setBackground(new java.awt.Color(153, 0, 153));
        ATTENDEE_PANEL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ATTENDEE_PANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upcomingevent2.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent2.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent2.setText("Attendee");
        ATTENDEE_PANEL.add(upcomingevent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        admin_label3.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label3.setForeground(new java.awt.Color(255, 255, 255));
        admin_label3.setText("Manage Attendee");
        ATTENDEE_PANEL.add(admin_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        deleteattenddetButton4.setBackground(new java.awt.Color(204, 204, 204));
        deleteattenddetButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteattenddetButton4.setText("DELETE");
        deleteattenddetButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteattenddetButton4ActionPerformed(evt);
            }
        });
        ATTENDEE_PANEL.add(deleteattenddetButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, 32));

        addattendeeButton.setBackground(new java.awt.Color(204, 204, 204));
        addattendeeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addattendeeButton.setText("ADD ");
        addattendeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addattendeeButtonActionPerformed(evt);
            }
        });
        ATTENDEE_PANEL.add(addattendeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 80, 32));

        editattendeetButton6.setBackground(new java.awt.Color(204, 204, 204));
        editattendeetButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editattendeetButton6.setText("EDIT ");
        editattendeetButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editattendeetButton6ActionPerformed(evt);
            }
        });
        ATTENDEE_PANEL.add(editattendeetButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, 32));

        backbutton2.setBackground(new java.awt.Color(204, 204, 204));
        backbutton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton2.setText("BACK");
        backbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton2ActionPerformed(evt);
            }
        });
        ATTENDEE_PANEL.add(backbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 129, 32));

        searchattendeelabel.setBackground(new java.awt.Color(153, 255, 255));
        searchattendeelabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchattendeelabelActionPerformed(evt);
            }
        });
        ATTENDEE_PANEL.add(searchattendeelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 150, 30));

        searchattendeebutton.setBackground(new java.awt.Color(204, 204, 204));
        searchattendeebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchattendeebutton.setText("SEARCH");
        searchattendeebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchattendeebuttonActionPerformed(evt);
            }
        });
        ATTENDEE_PANEL.add(searchattendeebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 90, 32));

        attendeetable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attendeetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ST2024-0001", "Andre M.", "Adiii@UN"},
                {"ST2024-00002", "Joemar A.", "Joemar@UN"},
                {"ST2024-0003", "Jan P.", "Jan@UN"},
                {"ST20240-0004", "Judi G.", "Judi@UN"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Attendee ID", "Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(attendeetable);

        ATTENDEE_PANEL.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 450, 210));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel18.setText("jLabel4");
        ATTENDEE_PANEL.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 500, 330));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ATTENDEE_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ATTENDEE_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TAB.addTab("ATTENDEES", jPanel4);

        SUPPLIESPANEL.setBackground(new java.awt.Color(153, 0, 153));
        SUPPLIESPANEL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SUPPLIESPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_label5.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label5.setForeground(new java.awt.Color(255, 255, 255));
        admin_label5.setText("Manage Supplies");
        SUPPLIESPANEL.add(admin_label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        upcomingevent3.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent3.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent3.setText("Events with supplies");
        SUPPLIESPANEL.add(upcomingevent3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        deletesuppliestButton.setBackground(new java.awt.Color(204, 204, 204));
        deletesuppliestButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletesuppliestButton.setText("DELETE");
        deletesuppliestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesuppliestButtonActionPerformed(evt);
            }
        });
        SUPPLIESPANEL.add(deletesuppliestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, 32));

        editsuppliesButton.setBackground(new java.awt.Color(204, 204, 204));
        editsuppliesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editsuppliesButton.setText("EDIT ");
        editsuppliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editsuppliesButtonActionPerformed(evt);
            }
        });
        SUPPLIESPANEL.add(editsuppliesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, 32));

        addsuppliesButton.setBackground(new java.awt.Color(204, 204, 204));
        addsuppliesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addsuppliesButton.setText("ADD ");
        addsuppliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsuppliesButtonActionPerformed(evt);
            }
        });
        SUPPLIESPANEL.add(addsuppliesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 80, 32));

        backbutton3.setBackground(new java.awt.Color(204, 204, 204));
        backbutton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton3.setText("BACK");
        backbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton3ActionPerformed(evt);
            }
        });
        SUPPLIESPANEL.add(backbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 129, 32));

        supplieastable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Supply Id", "Supplies Name", "Quantity", "Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(supplieastable);

        SUPPLIESPANEL.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 480, 220));

        searchsuppliesbutton.setBackground(new java.awt.Color(204, 204, 204));
        searchsuppliesbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchsuppliesbutton.setText("SEARCH");
        searchsuppliesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsuppliesbuttonActionPerformed(evt);
            }
        });
        SUPPLIESPANEL.add(searchsuppliesbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, 32));

        searchsupplieslabel.setBackground(new java.awt.Color(153, 255, 255));
        searchsupplieslabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsupplieslabelActionPerformed(evt);
            }
        });
        SUPPLIESPANEL.add(searchsupplieslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 150, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel19.setText("jLabel4");
        SUPPLIESPANEL.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 500, 330));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(SUPPLIESPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SUPPLIESPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TAB.addTab("SUPPLIES", jPanel5);

        ORGANIZERPANEL.setBackground(new java.awt.Color(153, 0, 153));
        ORGANIZERPANEL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ORGANIZERPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_label7.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        admin_label7.setForeground(new java.awt.Color(255, 255, 255));
        admin_label7.setText("Manage Organzer");
        ORGANIZERPANEL.add(admin_label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        upcomingevent4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent4.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent4.setText("List of Organizer");
        ORGANIZERPANEL.add(upcomingevent4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        searchorganizerbutton.setBackground(new java.awt.Color(204, 204, 204));
        searchorganizerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchorganizerbutton.setText("SEARCH");
        searchorganizerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchorganizerbuttonActionPerformed(evt);
            }
        });
        ORGANIZERPANEL.add(searchorganizerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 90, 32));

        searchorgaizerlabel.setBackground(new java.awt.Color(153, 255, 255));
        searchorgaizerlabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchorgaizerlabelActionPerformed(evt);
            }
        });
        ORGANIZERPANEL.add(searchorgaizerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 150, 30));

        deleteOrganizerButton.setBackground(new java.awt.Color(204, 204, 204));
        deleteOrganizerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteOrganizerButton.setText("DELETE");
        deleteOrganizerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrganizerButtonActionPerformed(evt);
            }
        });
        ORGANIZERPANEL.add(deleteOrganizerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, 32));

        editorganierButton.setBackground(new java.awt.Color(204, 204, 204));
        editorganierButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editorganierButton.setText("EDIT ");
        editorganierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorganierButtonActionPerformed(evt);
            }
        });
        ORGANIZERPANEL.add(editorganierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, 32));

        addorganizerButton.setBackground(new java.awt.Color(204, 204, 204));
        addorganizerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addorganizerButton.setText("ADD ");
        addorganizerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorganizerButtonActionPerformed(evt);
            }
        });
        ORGANIZERPANEL.add(addorganizerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 80, 32));

        backbutton4.setBackground(new java.awt.Color(204, 204, 204));
        backbutton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton4.setText("BACK");
        backbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton4ActionPerformed(evt);
            }
        });
        ORGANIZERPANEL.add(backbutton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 129, 32));

        organizertable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        organizertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ST2024-0001", "Andre M.", "Adiii@UN"},
                {"ST2024-00002", "Joemar A.", "Joemar@UN"},
                {"ST2024-0003", "Jan P.", "Jan@UN"},
                {"ST20240-0004", "Judi G.", "Judi@UN"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Organizer ID", "Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        organizertable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                organizertableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(organizertable);

        ORGANIZERPANEL.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 460, 220));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel20.setText("jLabel4");
        ORGANIZERPANEL.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 490, 330));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(ORGANIZERPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ORGANIZERPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TAB.addTab("ORGANIZERS", jPanel6);

        REPORTPANEL.setBackground(new java.awt.Color(153, 0, 153));
        REPORTPANEL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        REPORTPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upcomingevent5.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        upcomingevent5.setForeground(new java.awt.Color(255, 255, 255));
        upcomingevent5.setText("Reports");
        jPanel8.add(upcomingevent5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/attendee.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/feedback.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, 110));

        LISTATTENDEEBUTTON.setText("Attendee List");
        LISTATTENDEEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTATTENDEEBUTTONActionPerformed(evt);
            }
        });
        jPanel8.add(LISTATTENDEEBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 30));

        FEEDBACKSUMMARYBUTTON.setText("FeedBack Summary");
        FEEDBACKSUMMARYBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEEDBACKSUMMARYBUTTONActionPerformed(evt);
            }
        });
        jPanel8.add(FEEDBACKSUMMARYBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 150, 30));

        FINANCALBUTTON.setText("Financial Summary");
        FINANCALBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINANCALBUTTONActionPerformed(evt);
            }
        });
        jPanel8.add(FINANCALBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/financial.png"))); // NOI18N
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/staff.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 100));

        LISTORGANIZZERBUTTON.setText("Organizer List");
        LISTORGANIZZERBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTORGANIZZERBUTTONActionPerformed(evt);
            }
        });
        jPanel8.add(LISTORGANIZZERBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 30));

        backbutton6.setBackground(new java.awt.Color(204, 204, 204));
        backbutton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton6.setText("BACK");
        backbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton6ActionPerformed(evt);
            }
        });
        jPanel8.add(backbutton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 129, 32));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/staffSide.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, 110));

        suppliesbutton.setText("Supplies List");
        suppliesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliesbuttonActionPerformed(evt);
            }
        });
        jPanel8.add(suppliesbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 110, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        jLabel21.setText("jLabel4");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 520, 440));

        REPORTPANEL.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, 430));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(REPORTPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(REPORTPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TAB.addTab("REPORTS", jPanel7);

        jPanel2.add(TAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 570, 510));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        background.setText("jLabel2");
        jPanel2.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 790, 600));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashbourdbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashbourdbuttonActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(0);
    }//GEN-LAST:event_dashbourdbuttonActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        login log = new login();
        log.setLocationRelativeTo(null);
        log.setVisible(true); // Corrected typo here
        setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private void FINANCALBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINANCALBUTTONActionPerformed
       financialSUM list = new financialSUM();
       list.setLocationRelativeTo(null);
        list.setVisible(true); // Corrected typo here
        setVisible(false); 
    }//GEN-LAST:event_FINANCALBUTTONActionPerformed

    private void LISTATTENDEEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTATTENDEEBUTTONActionPerformed
    // TODO add your handling code here:
 
        LIST_attendee list = new LIST_attendee();
        list.setLocationRelativeTo(null);
        list.setVisible(true); // Corrected typo here
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LISTATTENDEEBUTTONActionPerformed

    private void LISTORGANIZZERBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTORGANIZZERBUTTONActionPerformed
   LIST_organizer list = new LIST_organizer();
   list.setLocationRelativeTo(null);
        list.setVisible(true); // Corrected typo here
        setVisible(false);   
    }//GEN-LAST:event_LISTORGANIZZERBUTTONActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(0);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void addEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventButtonActionPerformed

        choice = 1; // Correctly update the choice variable        // TODO add your handling code here:
        ADD_event add = new ADD_event(choice,"", "", "", "", "", "");
        add.setLocationRelativeTo(null);
        add.setVisible(true); // Corrected typo here
        setVisible(false);
    }//GEN-LAST:event_addEventButtonActionPerformed

    private void deleteattenddetButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteattenddetButton4ActionPerformed
 choice = 1; // Correctly update the choice variable
        DELETE_attendee delete = new  DELETE_attendee(choice);
        delete.setLocationRelativeTo(null);
        delete.setVisible(true); // Corrected typo here
        setVisible(false);   
    }//GEN-LAST:event_deleteattenddetButton4ActionPerformed

    private void addattendeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addattendeeButtonActionPerformed
     choice = 1; // Correctly update the choice variable
    ADD_attendee add = new ADD_attendee(choice, "", ""); // Pass the choice value to the constructor
    add.setLocationRelativeTo(null);
    add.setVisible(true); // Corrected typo here
    setVisible(false);     
    }//GEN-LAST:event_addattendeeButtonActionPerformed

    private void searchorganizerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchorganizerbuttonActionPerformed
           String searchTerm = searchorgaizerlabel.getText().trim();
    loadOrganizers(searchTerm);  // Load organizers based on search term
    }//GEN-LAST:event_searchorganizerbuttonActionPerformed

    private void searchorgaizerlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchorgaizerlabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchorgaizerlabelActionPerformed

    private void editattendeetButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editattendeetButton6ActionPerformed
    choice = 1; // Correctly update the choice variable

        EDIT_attendee edit = new  EDIT_attendee(choice);
        edit.setLocationRelativeTo(null);
        edit.setVisible(true); // Corrected typo here
        setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_editattendeetButton6ActionPerformed

    private void deletesuppliestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesuppliestButtonActionPerformed
    DELETE_supplies delete = new   DELETE_supplies();
    delete.setLocationRelativeTo(null);
        delete.setVisible(true); // Corrected typo here
        setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_deletesuppliestButtonActionPerformed

    private void editsuppliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editsuppliesButtonActionPerformed
       EDIT_supplies edit = new   EDIT_supplies();
       edit.setLocationRelativeTo(null);
        edit.setVisible(true); // Corrected typo here
        setVisible(false);      
    }//GEN-LAST:event_editsuppliesButtonActionPerformed

    private void addsuppliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsuppliesButtonActionPerformed
    ADD_supplies add = new   ADD_supplies( "", "", "");
    add.setLocationRelativeTo(null);
        add.setVisible(true); // Corrected typo here
        setVisible(false);            // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_addsuppliesButtonActionPerformed

    private void deleteOrganizerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrganizerButtonActionPerformed
        DELETE_organizer delete = new DELETE_organizer();
        delete.setLocationRelativeTo(null);
        delete.setVisible(true); // Corrected typo here
        setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_deleteOrganizerButtonActionPerformed

    private void editorganierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorganierButtonActionPerformed
      EDIT_organizer edit = new EDIT_organizer();
      edit.setLocationRelativeTo(null);
        edit.setVisible(true); // Corrected typo here
        setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_editorganierButtonActionPerformed

    private void addorganizerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorganizerButtonActionPerformed
         ADD_organizer add = new ADD_organizer("", "", ""); // Initialize with empty values
         add.setLocationRelativeTo(null);
        add.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_addorganizerButtonActionPerformed

    private void editEventbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEventbuttonActionPerformed
      choice = 1; // Correctly update the choice variable        // TODO add your handling code here:
        EDIT_event edit = new EDIT_event(choice);
        edit.setLocationRelativeTo(null);
        edit.setVisible(true); // Corrected typo here
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_editEventbuttonActionPerformed

    private void manageeventbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageeventbuttonActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(1);
    }//GEN-LAST:event_manageeventbuttonActionPerformed

    private void manageattendeebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageattendeebuttonActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(2);
    }//GEN-LAST:event_manageattendeebuttonActionPerformed

    private void managesuppliesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managesuppliesbuttonActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(3);
    }//GEN-LAST:event_managesuppliesbuttonActionPerformed

    private void manageorganizerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageorganizerbuttonActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(4);
    }//GEN-LAST:event_manageorganizerbuttonActionPerformed

    private void viewreportsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreportsbuttonActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(5);
    }//GEN-LAST:event_viewreportsbuttonActionPerformed

    private void backbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton1ActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(0);
    }//GEN-LAST:event_backbutton1ActionPerformed

    private void backbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton2ActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(0);
    }//GEN-LAST:event_backbutton2ActionPerformed

    private void backbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton3ActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(0);
    }//GEN-LAST:event_backbutton3ActionPerformed

    private void backbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton4ActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(0);
    }//GEN-LAST:event_backbutton4ActionPerformed

    private void backbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton6ActionPerformed
        // TODO add your handling code here:
        TAB.setSelectedIndex(0);
        
    }//GEN-LAST:event_backbutton6ActionPerformed

    private void suppliesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliesbuttonActionPerformed
        // TODO add your handling code here:
        LIST_supplies list = new LIST_supplies();
        list.setLocationRelativeTo(null);
        list.setVisible(true); // Corrected typo here
        setVisible(false);
    }//GEN-LAST:event_suppliesbuttonActionPerformed

    private void FEEDBACKSUMMARYBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEEDBACKSUMMARYBUTTONActionPerformed
        feedbackSUM list = new  feedbackSUM ();
        list.setLocationRelativeTo(null);
        list.setVisible(true); // Corrected typo here
        setVisible(false);           // TODO add your handling code here:
    }//GEN-LAST:event_FEEDBACKSUMMARYBUTTONActionPerformed

    private void organizertableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_organizertableAncestorAdded

    }//GEN-LAST:event_organizertableAncestorAdded

    private void countorganizerAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_countorganizerAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_countorganizerAncestorAdded

    private void listbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbuttonActionPerformed
      choice = 1; // Correctly update the choice variable     
        LIST_event list = new LIST_event(choice);
        list.setLocationRelativeTo(null);
        list.setVisible(true); // Corrected typo here
        setVisible(false);  
        
        
        
    }//GEN-LAST:event_listbuttonActionPerformed

    private void deleteEventButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEventButton3ActionPerformed
          // TODO add your handling code here:
        DELETE_event delete = new DELETE_event();
        delete.setLocationRelativeTo(null);
        delete.setVisible(true); // Corrected typo here
        setVisible(false);  
        
    }//GEN-LAST:event_deleteEventButton3ActionPerformed

    private void attendeecountAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_attendeecountAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_attendeecountAncestorAdded

    private void searcheventbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcheventbuttonActionPerformed
        String searchTerm = searcheventlabel.getText().trim();
        loadEvents(searchTerm);
    }//GEN-LAST:event_searcheventbuttonActionPerformed

    private void searcheventlabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcheventlabelActionPerformed

    }//GEN-LAST:event_searcheventlabelActionPerformed

    private void searchattendeelabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchattendeelabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchattendeelabelActionPerformed

    private void searchattendeebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchattendeebuttonActionPerformed
        String searchTerm = searchattendeelabel.getText().trim();
        loadAttendee(searchTerm);
    }//GEN-LAST:event_searchattendeebuttonActionPerformed

    private void countanttendeeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_countanttendeeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_countanttendeeAncestorAdded

    private void countsuppliesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_countsuppliesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_countsuppliesAncestorAdded

    private void searchsuppliesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsuppliesbuttonActionPerformed
        String searchTerm = searchsupplieslabel.getText().trim();
        loadSupplies(searchTerm);
    }//GEN-LAST:event_searchsuppliesbuttonActionPerformed

    private void searchsupplieslabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsupplieslabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchsupplieslabelActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
 private void loadOrganizers(String searchTerm) {
    DefaultTableModel model = (DefaultTableModel) organizertable.getModel();
    model.setRowCount(0);  // Clear existing data

    String sql = "SELECT * FROM organizers WHERE id = ? OR username LIKE ? OR contact LIKE ?";

    try (Connection connection = DatabaseManager.getConnection();
         PreparedStatement pstmt = connection.prepareStatement(sql)) {

        if (searchTerm.matches("\\d+")) {  // Check if the searchTerm is numeric (ID)
            pstmt.setInt(1, Integer.parseInt(searchTerm));
        } else {
            pstmt.setNull(1, java.sql.Types.INTEGER);
        }
        
        pstmt.setString(2, "%" + searchTerm + "%");  // Set the search term for username
        pstmt.setString(3, "%" + searchTerm + "%");  // Set the search term for contact

        try (ResultSet rs = pstmt.executeQuery()) {
            int count = 0;
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("username");
                String contact = rs.getString("contact");

                model.addRow(new Object[]{id, name, contact});
                count++;
            }
            countorganizer.setText(String.valueOf(count));  // Update the count label
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
}
 
private void loadEvents(String searchTerm) {
        DefaultTableModel model = (DefaultTableModel) eventtable.getModel();
        model.setRowCount(0); // Clear existing data

        String sql = "SELECT * FROM events WHERE id LIKE ? OR name LIKE ? OR date LIKE ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            String likeSearchTerm = "%" + searchTerm + "%";
            pstmt.setString(1, likeSearchTerm);
            pstmt.setString(2, likeSearchTerm);
            pstmt.setString(3, likeSearchTerm);

            try (ResultSet rs = pstmt.executeQuery()) {
                int count = 0;
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("name"),
                        rs.getString("date"),
                        rs.getString("time"),
                        rs.getString("duration"),
                        rs.getString("venue"),
                        rs.getString("description")
                    });
                    count++;
                }
                attendeecount.setText(String.valueOf(count));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Failed to load events: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

private void loadEvent(String searchTerm) {
        DefaultTableModel model = (DefaultTableModel) eventtable1.getModel();
        model.setRowCount(0); // Clear existing data

        String sql = "SELECT * FROM events WHERE id LIKE ? OR name LIKE ? OR date LIKE ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            String likeSearchTerm = "%" + searchTerm + "%";
            pstmt.setString(1, likeSearchTerm);
            pstmt.setString(2, likeSearchTerm);
            pstmt.setString(3, likeSearchTerm);

            try (ResultSet rs = pstmt.executeQuery()) {
                int count = 0;
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("name"),
                        rs.getString("date"),
                        rs.getString("time"),
                        rs.getString("duration"),
                        rs.getString("venue"),
                        rs.getString("description")
                    });
                    count++;
                }
                attendeecount.setText(String.valueOf(count));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Failed to load events: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     
private void loadAttendee(String searchTerm) {
        DefaultTableModel model = (DefaultTableModel) attendeetable.getModel();
        model.setRowCount(0);  // Clear existing data

        String sql = "SELECT * FROM attendees WHERE id = ? OR name LIKE ? OR email LIKE ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setString(1, "%" + searchTerm + "%");
            pstmt.setString(2, "%" + searchTerm + "%");
            pstmt.setString(3, "%" + searchTerm + "%");

            try (ResultSet rs = pstmt.executeQuery()) {
                int count = 0;
                while (rs.next()) {
                    int id = rs.getInt("id");
                    String name = rs.getString("name");
                    String email = rs.getString("email");

                    model.addRow(new Object[]{id, name, email});
                    count++;
                }
                attendeecount.setText(String.valueOf(count));  // Update the count label
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

 private void loadSupplies(String searchTerm) {
    DefaultTableModel model = (DefaultTableModel) supplieastable.getModel();
    model.setRowCount(0);  // Clear existing data

    // Update the SQL query to exclude the total calculation
    String sql = "SELECT id, name, quantity, price FROM supplies WHERE id LIKE ? OR name LIKE ?";

    try (Connection connection = DatabaseManager.getConnection();
         PreparedStatement pstmt = connection.prepareStatement(sql)) {

        pstmt.setString(1, "%" + searchTerm + "%");
        pstmt.setString(2, "%" + searchTerm + "%");

        try (ResultSet rs = pstmt.executeQuery()) {
            int count = 0;
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                int quantity = rs.getInt("quantity");
                double price = rs.getDouble("price");

                // Calculate the total manually
                double total = quantity * price;

                model.addRow(new Object[]{id, name, quantity, price, total});
                count++;
            }
            countsupplies.setText(String.valueOf(count));  // Update the count label
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ATTENDEE_PANEL;
    private javax.swing.JPanel EVENT;
    private javax.swing.JButton FEEDBACKSUMMARYBUTTON;
    private javax.swing.JButton FINANCALBUTTON;
    private javax.swing.JButton LISTATTENDEEBUTTON;
    private javax.swing.JButton LISTORGANIZZERBUTTON;
    private javax.swing.JPanel ORGANIZERPANEL;
    private javax.swing.JPanel Product_Panel3;
    private javax.swing.JPanel Product_Panel4;
    private javax.swing.JPanel Product_Panel5;
    private javax.swing.JPanel REPORTPANEL;
    private javax.swing.JPanel SUPPLIESPANEL;
    private javax.swing.JLabel Suppliescount;
    private javax.swing.JTabbedPane TAB;
    private javax.swing.JButton addEventButton;
    private javax.swing.JButton addattendeeButton;
    private javax.swing.JButton addorganizerButton;
    private javax.swing.JButton addsuppliesButton;
    private javax.swing.JLabel admin_label;
    private javax.swing.JLabel admin_label1;
    private javax.swing.JLabel admin_label3;
    private javax.swing.JLabel admin_label5;
    private javax.swing.JLabel admin_label7;
    private javax.swing.JLabel attendeecount;
    private javax.swing.JLabel attendeelabel1;
    private javax.swing.JTable attendeetable;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton backbutton1;
    private javax.swing.JButton backbutton2;
    private javax.swing.JButton backbutton3;
    private javax.swing.JButton backbutton4;
    private javax.swing.JButton backbutton6;
    private javax.swing.JLabel background;
    private javax.swing.JLabel countanttendee;
    private javax.swing.JLabel countorganizer;
    private javax.swing.JLabel countsupplies;
    private javax.swing.JPanel dashbourd;
    private javax.swing.JButton dashbourdbutton;
    private javax.swing.JButton deleteEventButton3;
    private javax.swing.JButton deleteOrganizerButton;
    private javax.swing.JButton deleteattenddetButton4;
    private javax.swing.JButton deletesuppliestButton;
    private javax.swing.JButton editEventbutton;
    private javax.swing.JButton editattendeetButton6;
    private javax.swing.JButton editorganierButton;
    private javax.swing.JButton editsuppliesButton;
    private javax.swing.JTable eventtable;
    private javax.swing.JTable eventtable1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel hiadmin_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton listbutton;
    private javax.swing.JButton manageattendeebutton;
    private javax.swing.JButton manageeventbutton;
    private javax.swing.JButton manageorganizerbutton;
    private javax.swing.JButton managesuppliesbutton;
    private javax.swing.JLabel organizerlabel2;
    private javax.swing.JTable organizertable;
    private javax.swing.JButton searchattendeebutton;
    private javax.swing.JTextField searchattendeelabel;
    private javax.swing.JButton searcheventbutton;
    private javax.swing.JTextField searcheventlabel;
    private javax.swing.JTextField searchorgaizerlabel;
    private javax.swing.JButton searchorganizerbutton;
    private javax.swing.JButton searchsuppliesbutton;
    private javax.swing.JTextField searchsupplieslabel;
    private javax.swing.JTable supplieastable;
    private javax.swing.JButton suppliesbutton;
    private javax.swing.JLabel upcomingevent;
    private javax.swing.JLabel upcomingevent1;
    private javax.swing.JLabel upcomingevent2;
    private javax.swing.JLabel upcomingevent3;
    private javax.swing.JLabel upcomingevent4;
    private javax.swing.JLabel upcomingevent5;
    private javax.swing.JButton viewreportsbutton;
    // End of variables declaration//GEN-END:variables
}
