/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminMenu.eventsmanengment;

import AdminMenu.Admin;
import AttendeeMenu.logattendee;
import OrganizerMenu.Organizer;
import ocatve.DatabaseManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import ocatve.login;

/**
 *
 * @author Anggo
 */
public class ADD_event extends javax.swing.JFrame {
    
    private int choice;
    private Object TAB;
    private String name;
    private String date;
    private String time;
    private String duration;
    private String venue;
    private String description;
    
    public ADD_event(int choice, String name, String date, String time, String duration, String venue, String description) {
        this.choice = choice;
        this.name = name;
        this.date = date;
        this.time = time;
        this.duration = duration;
        this.venue = venue;
        this.description = description;
        initComponents();
    }

    // Getters
    public int getChoice() {
        return choice;
    }

    public String getName() {
        return name;
    }

    public String getDate() {
        return date;
    }

    public String getTime() {
        return time;
    }

    public String getDuration() {
        return duration;
    }

    public String getVenue() {
        return venue;
    }

    public String getDescription() {
        return description;
    }

    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eventNameLabel = new javax.swing.JTextField();
        dateNameLabel = new javax.swing.JTextField();
        timeNameLabel = new javax.swing.JTextField();
        durationNameLabel = new javax.swing.JTextField();
        venueNameLabel = new javax.swing.JTextField();
        descriptionNameLabel = new javax.swing.JTextField();
        addEventbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("DELETE EVENT");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/event.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 6, 100, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Date :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Time:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Duration:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Venue:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 18));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Description");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, -1));

        eventNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(eventNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, -1));

        dateNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(dateNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, 30));

        timeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(timeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 100, -1));

        durationNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        durationNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(durationNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, -1));

        venueNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        venueNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venueNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(venueNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, -1));

        descriptionNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(descriptionNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 100, -1));

        addEventbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addEventbutton.setText("ADD");
        addEventbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(addEventbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 40));

        cancelbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelbutton.setText("CANCEL");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 90, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("ADD EVENT");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 112, -1, -1));

        jLabel12.setText("(yyyy-MM-dd)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEventbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventbuttonActionPerformed
     String name = eventNameLabel.getText();
        String date = dateNameLabel.getText();
        String time = timeNameLabel.getText();
        String duration = durationNameLabel.getText();
        String venue = venueNameLabel.getText();
        String description = descriptionNameLabel.getText();



      addEvent(name, date,  time,duration,venue, description);
        
    
    }//GEN-LAST:event_addEventbuttonActionPerformed

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
      switch (choice) {
        case 1:
            Admin admin = new Admin();
            admin.setLocationRelativeTo(null);
            admin.setVisible(true);  
            admin.getTabPane().setSelectedIndex(1); // Access TAB via the Admin instance
            setVisible(false);
            break;
        case 2:
            Organizer organizer = new Organizer();
            organizer.setLocationRelativeTo(null);
            organizer.setVisible(true);
            organizer.getTabPane().setSelectedIndex(0); // Access TAB via the Admin instance
            setVisible(false);
            break;
        case 3:
            logattendee attendee = new logattendee();
            attendee.setLocationRelativeTo(null);
            attendee.setVisible(true);
            setVisible(false);
            break;
        default:
            // Handle the default case if needed
            System.out.println("Invalid choice: " + choice);
            break;
    }
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void descriptionNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionNameLabelActionPerformed

    private void eventNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameLabelActionPerformed

    private void dateNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNameLabelActionPerformed

    private void timeNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeNameLabelActionPerformed

    private void durationNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationNameLabelActionPerformed

    private void venueNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venueNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venueNameLabelActionPerformed

    /**
     * @param args the command line arguments
     */
 // Method to validate date format
    
     private void addEvent(String name, String date, String time, String duration, String venue, String description) {
    if (name.isEmpty() || date.isEmpty() || time.isEmpty() || duration.isEmpty() || venue.isEmpty() || description.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!isValidDate(date)) {
        JOptionPane.showMessageDialog(this, "Please enter a valid date in the format yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (DatabaseManager.eventExists(name, date, time, duration, venue, description)) {
        JOptionPane.showMessageDialog(this, "An event with the same details already exists.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Insert event into the database
    DatabaseManager.insertEvent(name.trim(), date.trim(), time.trim(), duration.trim(), venue.trim(), description.trim());

    eventNameLabel.setText("");
    dateNameLabel.setText("");
    timeNameLabel.setText("");
    durationNameLabel.setText("");
    venueNameLabel.setText("");
    descriptionNameLabel.setText("");
}

private boolean isValidDate(String date) {
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    sdf.setLenient(false);
    try {
        sdf.parse(date);
    } catch (ParseException e) {
        return false;
    }
    return true;
}

 
    
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // ... existing Nimbus look and feel setup code ...

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
            int choice = 0; // Default value, should be set according to your logic
            login loginInstance = new login(); // Assuming login is the class name
            if (loginInstance.adminbuttonLOG.isSelected()) {
                choice = 1;
            } else if (loginInstance.organizerbuttonLOG.isSelected()) {
                choice = 2;
            }
            
            new ADD_event(choice, "", "", "", "", "", "").setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEventbutton;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JTextField dateNameLabel;
    private javax.swing.JTextField descriptionNameLabel;
    private javax.swing.JTextField durationNameLabel;
    private javax.swing.JTextField eventNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField timeNameLabel;
    private javax.swing.JTextField venueNameLabel;
    // End of variables declaration//GEN-END:variables
}
