/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminMenu.eventsmanengment;

import AdminMenu.Admin;
import AttendeeMenu.logattendee;
import OrganizerMenu.Organizer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import ocatve.DatabaseManager;
/**
 *
 * @author Anggo
 */
public class EDIT_event extends javax.swing.JFrame {
 private int choice;
    /**
     * Creates new form EDIT_event
     */
    public EDIT_event(int choice) {
        this.choice = choice;
        initComponents();
    }
    private EDIT_event() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addProductBT = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        searchBT = new javax.swing.JButton();
        IDNameLabel = new javax.swing.JTextField();
        eventNameLabel = new javax.swing.JTextField();
        dateNameLabel = new javax.swing.JTextField();
        timeNameLabel = new javax.swing.JTextField();
        durationNameLabel = new javax.swing.JTextField();
        venueNameLabel = new javax.swing.JTextField();
        descriptionNameLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editevent.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 177, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 209, 50, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Time:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 239, 50, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Duration:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 269, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Venue:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 300, 50, 18));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Description");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 329, 80, -1));

        addProductBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addProductBT.setText("SAVE");
        addProductBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBTActionPerformed(evt);
            }
        });
        jPanel1.add(addProductBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 90, 40));

        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBT.setText("CANCEL");
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 90, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("EVENT ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 143, 80, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EDIT EVENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        searchBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBT.setText("SEARCH");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        jPanel1.add(searchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 80, 26));

        IDNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IDNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(IDNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 77, -1));

        eventNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(eventNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 170, -1));

        dateNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(dateNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, -1));

        timeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(timeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 170, -1));

        durationNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        durationNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(durationNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 170, -1));

        venueNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        venueNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venueNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(venueNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 170, -1));

        descriptionNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(descriptionNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 38, 280, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 310, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBTActionPerformed
    // Validate inputs
        if (IDNameLabel.getText().trim().isEmpty() ||
            eventNameLabel.getText().trim().isEmpty() ||
            dateNameLabel.getText().trim().isEmpty() ||
            timeNameLabel.getText().trim().isEmpty() ||
            durationNameLabel.getText().trim().isEmpty() ||
            venueNameLabel.getText().trim().isEmpty() ||
            descriptionNameLabel.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int eventID = Integer.parseInt(IDNameLabel.getText().trim());

            // Call the update method
            updateEvent(eventID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Event ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addProductBTActionPerformed

    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTActionPerformed
 switch (choice) {
        case 1:
            Admin admin = new Admin();
            admin.setLocationRelativeTo(null);
            admin.setVisible(true);
            admin.getTabPane().setSelectedIndex(1); // Access TAB via the Admin instance
            setVisible(false);
            break;
        case 2:
            Organizer organizer = new Organizer();
            organizer.setLocationRelativeTo(null);
            organizer.setVisible(true);
            organizer.getTabPane().setSelectedIndex(0); // Access TAB via the Admin instance
            setVisible(false);
            break;
        case 3:
            logattendee attendee = new logattendee();
            attendee.setLocationRelativeTo(null);
            attendee.setVisible(true);
            setVisible(false);
            break;
        default:
            // Handle the default case if needed
            System.out.println("Invalid choice: " + choice);
            break;
    }
    }//GEN-LAST:event_cancelBTActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
 try {
            int eventID = Integer.parseInt(IDNameLabel.getText());
            searchEvent(eventID);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Event ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBTActionPerformed

    private void IDNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDNameLabelActionPerformed

    private void eventNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameLabelActionPerformed

    private void dateNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNameLabelActionPerformed

    private void timeNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeNameLabelActionPerformed

    private void durationNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationNameLabelActionPerformed

    private void venueNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venueNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venueNameLabelActionPerformed

    private void descriptionNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionNameLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void searchEvent(int eventID) {
        String sql = "SELECT * FROM events WHERE id = ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setInt(1, eventID);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                eventNameLabel.setText(rs.getString("name"));
                dateNameLabel.setText(rs.getString("date"));
                timeNameLabel.setText(rs.getString("time"));
                durationNameLabel.setText(rs.getString("duration"));
                venueNameLabel.setText(rs.getString("venue"));
                descriptionNameLabel.setText(rs.getString("description"));
            } else {
                JOptionPane.showMessageDialog(null, "Event not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
   private void updateEvent(int eventID) {
        String name = eventNameLabel.getText().trim();
        String date = dateNameLabel.getText().trim();
        String time = timeNameLabel.getText().trim();
        String duration = durationNameLabel.getText().trim();
        String venue = venueNameLabel.getText().trim();
        String description = descriptionNameLabel.getText().trim();

        String sql = "UPDATE events SET name = ?, date = ?, time = ?, duration = ?, venue = ?, description = ? WHERE id = ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setString(1, name);
            pstmt.setString(2, date);
            pstmt.setString(3, time);
            pstmt.setString(4, duration);
            pstmt.setString(5, venue);
            pstmt.setString(6, description);
            pstmt.setInt(7, eventID);

            int rowsUpdated = pstmt.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Event updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                // Clear fields if necessary
                eventNameLabel.setText("");
                dateNameLabel.setText("");
                timeNameLabel.setText("");
                durationNameLabel.setText("");
                venueNameLabel.setText("");
                descriptionNameLabel.setText("");
                IDNameLabel.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "No event found with the given ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDIT_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDIT_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDIT_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDIT_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDIT_event().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDNameLabel;
    private javax.swing.JButton addProductBT;
    private javax.swing.JButton cancelBT;
    private javax.swing.JTextField dateNameLabel;
    private javax.swing.JTextField descriptionNameLabel;
    private javax.swing.JTextField durationNameLabel;
    private javax.swing.JTextField eventNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchBT;
    private javax.swing.JTextField timeNameLabel;
    private javax.swing.JTextField venueNameLabel;
    // End of variables declaration//GEN-END:variables
}
