/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminMenu.attendeemanagement;

import AdminMenu.Admin;
import AttendeeMenu.logattendee;
import OrganizerMenu.Organizer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import ocatve.DatabaseManager;

/**
 *
 * @author Anggo
 */
public class DELETE_attendee extends javax.swing.JFrame {
private int choice;
    /**
     * Creates new form DELETE_event
     */
    public DELETE_attendee(int choice) {
        this.choice = choice;
        initComponents();
    }

    private DELETE_attendee() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        attendeeNameLabel = new javax.swing.JTextField();
        attendeeEmailLabel = new javax.swing.JTextField();
        deletebutton = new javax.swing.JButton();
        cancelBT = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        attendeeIDLabel = new javax.swing.JTextField();
        searchBT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/attendee.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 103, 100));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Attendee ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Contact:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, -1));

        attendeeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attendeeNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendeeNameLabelActionPerformed(evt);
            }
        });
        jPanel1.add(attendeeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, -1));

        attendeeEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attendeeEmailLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendeeEmailLabelActionPerformed(evt);
            }
        });
        jPanel1.add(attendeeEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, -1));

        deletebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 102, 40));

        cancelBT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelBT.setText("CANCEL");
        cancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 90, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("DELETE ATTENDEE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        attendeeIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attendeeIDLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendeeIDLabelActionPerformed(evt);
            }
        });
        jPanel1.add(attendeeIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 77, -1));

        searchBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBT.setText("SEARCH");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        jPanel1.add(searchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 80, 26));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mainbackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 400, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendeeNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendeeNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendeeNameLabelActionPerformed

    private void attendeeEmailLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendeeEmailLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendeeEmailLabelActionPerformed

    private void cancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTActionPerformed
switch (choice) {
        case 1:
            Admin admin = new Admin();
            admin.setLocationRelativeTo(null);
            admin.setVisible(true);
            admin.getTabPane().setSelectedIndex(2); // Access TAB via the Admin instance
            setVisible(false);
            break;
        case 2:
            Organizer organizer = new Organizer();
            organizer.setLocationRelativeTo(null);
            organizer.setVisible(true);
            organizer.getTabPane().setSelectedIndex(1); // Access TAB via the Admin instance
            setVisible(false);
            break;
        case 3:
            logattendee attendee = new logattendee();
            attendee.setLocationRelativeTo(null);
            attendee.setVisible(true);
            setVisible(false);
            break;
        default:
            // Handle the default case if needed
            System.out.println("Invalid choice: " + choice);
            break;
    }
    }//GEN-LAST:event_cancelBTActionPerformed

    private void attendeeIDLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendeeIDLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendeeIDLabelActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
  int attendeeID  = Integer.parseInt(attendeeIDLabel.getText());
        searchAttendee(attendeeID );
    }//GEN-LAST:event_searchBTActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
  int attendeeID = Integer.parseInt(attendeeIDLabel.getText());
        deleteAttendee(attendeeID );
    }//GEN-LAST:event_deletebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    
     private void searchAttendee(int attendeeID) {
        String sql = "SELECT * FROM attendees WHERE id = ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setInt(1, attendeeID);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                attendeeNameLabel.setText(rs.getString("name"));
                attendeeEmailLabel.setText(rs.getString("email"));
               
            } else {
                JOptionPane.showMessageDialog(null, "Attendees not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed to search for the Attendees.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

   private void deleteAttendee(int attendeeID) {
        String sql = "DELETE FROM attendees WHERE id = ?";

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(sql)) {

            pstmt.setInt(1, attendeeID);
            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Attendees deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
               attendeeNameLabel.setText("");
               attendeeEmailLabel.setText("");
                attendeeIDLabel.setText("");
                
            } else {
                JOptionPane.showMessageDialog(null, "Attendees not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Failed to delete the Attendees.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE_attendee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE_attendee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE_attendee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE_attendee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE_attendee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attendeeEmailLabel;
    private javax.swing.JTextField attendeeIDLabel;
    private javax.swing.JTextField attendeeNameLabel;
    private javax.swing.JButton cancelBT;
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchBT;
    // End of variables declaration//GEN-END:variables
}
